[Grpc]
Appid="mqsync"
Address="10.1.1.248:10000"

[LogService]
Appid="mqsync"
Address="10.1.1.248:10001"

[ConnectionString]
DataCenter="root:pwd@(10.1.1.245:3306)/dbname?charset=utf8"
RabbitMq="amqp://admin:admin@10.1.1.248:5672/"