[Grpc]
Appid="mqsync"
Address="10.1.1.248:10000"

[LogService]
Appid="mqsync"
Address="10.1.1.248:10001"

[Mysql]
Host="10.1.1.245"
Port=3306
User="root"
Pwd=""
Default="datacenter"

[Mq]
HostName="10.1.1.248:5672"
EndPoint=""
UserName="admin"
PassWord="admin"
